Remove and reinstall BMO in source cluster before and after pivot
metal3-io/metal3-dev-env pull request #1143
Opened 2023-01-24 10:07 UTC by kashifest

2023-01-24 10:07 UTC, kashifest commented
/test-ubuntu-integration-main 
/test-centos-integration-release-1-3

2023-01-24 10:08 UTC, kashifest commented
/test-upgrade-features
/test-features-ubuntu

2023-01-24 10:20 UTC, kashifest commented
/test-ubuntu-integration-main
/test-centos-integration-release-1-3
/test-upgrade-features
/test-features-ubuntu

2023-01-24 10:21 UTC, kashifest commented
/test-ubuntu-integration-main
/test-centos-integration-release-1-3
/test-upgrade-features
/test-features-ubuntu

2023-01-27 12:44 UTC, mboukhalfa commented
> Remove and reinstall BMO in source cluster before and after pivot
We remove Ironic because it becomes conflicting with the new instance in the target but why we should remove and install bmo as well ?

2023-01-27 13:03 UTC, kashifest commented
> > Remove and reinstall BMO in source cluster before and after pivot
> 
> We remove Ironic because it becomes conflicting with the new instance in the target but why we should remove and install bmo as well ?

This is something which was discussed in ESJ CI discussion. It was reported that the BMO is unable to reconnect with Ironic when Ironic is moved back to the source cluster. Furthermore this issue might have something to do with a previously reported BMO issue:
https://github.com/metal3-io/baremetal-operator/issues/1085#issuecomment-1042501596.

We concluded that as a possible solution we will delete and reinstate BMO also as we do for ironic.

2023-01-31 12:39 UTC, lentzi90 reviewed
/lgtm
I was thinking that it might be easier to scale to 0 and then scale up again instead of delete and recreate. But this seems to work so why not.

2023-01-31 12:41 UTC, kashifest commented
good point. Since this more seemed like a BMO caching issue to me, I am more inclined towards deleting the deploy in recreating it rather. 

> /lgtm I was thinking that it might be easier to scale to 0 and then scale up again instead of delete and recreate. But this seems to work so why not.

2023-01-31 13:10 UTC, Rozzii commented
/approve

2023-01-31 14:56 UTC, Sunnatillo commented
/lgtm

2023-02-23 09:10 UTC, mboukhalfa commented
/test-centos-integration-e2e-main

2023-02-23 09:13 UTC, mboukhalfa commented
/test-ubuntu-integration-e2e-main

2023-02-27 19:03 UTC, furkatgofurov7 approved these changes

2023-03-01 19:35 UTC, kashifest commented
/hold

2023-04-03 13:34 UTC, tuminoid commented
/lgtm cancel

Just testing something, this needs work anyways.

2023-04-13 14:04 UTC, mboukhalfa commented
/hold cancel

2023-04-13 14:06 UTC, mboukhalfa commented
/test-centos-integration-release-1-3
/test-ubuntu-e2e-integration-main

2023-04-14 11:49 UTC, Sunnatillo reviewed
/lgtm

2023-04-14 12:04 UTC, lentzi90 requested changes

2023-04-14 12:04 UTC, lentzi90 commented on tests/roles/run_tests/tasks/move_back.yml
> +    shell: "{{ BMOPATH }}/tools/deploy.sh true false {{ IRONIC_TLS_SETUP }} {{ IRONIC_BASIC_AUTH }} true"
The positional arguments [are deprecated](https://github.com/metal3-io/baremetal-operator/blob/ae34635a1e038ff42333bb3c952f5b9bfe301b83/tools/deploy.sh#L63). We should do it like for Ironic below.

```suggestion
    shell: "{{ BMOPATH }}/tools/deploy.sh -b {{ BMO_IRONIC_ARGS }}"
```

The variable that sets the arguments is already correctly set [here](https://github.com/metal3-io/metal3-dev-env/blob/c343d5648572da58cea1072d1e99b3a6b3632b1a/tests/roles/run_tests/vars/main.yml#L91) so we can use it directly. Just need to add `-b` for BMO.

Are you sure we should use `KUBECTL_ARGS` here btw? It is not used for Ironic below and I would assume it should be the same here.

2023-04-14 12:22 UTC, mboukhalfa commented
/test-centos-integration-release-1-3
/test-ubuntu-e2e-integration-main

2023-06-21 07:44 UTC, lentzi90 reviewed
/approve

2023-06-21 07:44 UTC, lentzi90 commented
/test-centos-integration-release-1-4

2023-06-21 07:48 UTC, mboukhalfa commented
/test-ubuntu-e2e-integration-main

2023-06-21 08:13 UTC, mboukhalfa commented
/lgtm

2023-06-21 08:31 UTC, merged