fix ironic building from source in PR test
metal3-io/metal3-dev-env pull request #1330
Opened 2023-12-21 14:15 UTC by tuminoid

In a PR, repo being tested is cloned as tested_repo. This doesn't match "ironic-image" like it normally would, and Ironic is not built from soruce. Same issue with CAPI. Identify the local image via the prefix of the LOCAL_IMAGE variable rather than the variable content (repo path).

2023-12-21 14:16 UTC, tuminoid commented
/test-ubuntu-integration-main
/test-centos-integration-main

2023-12-21 14:16 UTC, tuminoid commented
/hold
until local testing finishes.

2023-12-22 06:00 UTC, tuminoid commented
/unhold
Worked as expected.
/cc @Sunnatillo @smoshiur1237 @lentzi90 @Rozzii

2023-12-22 06:00 UTC, tuminoid commented
/test-centos-integration-release-1-5  
/test-ubuntu-e2e-integration-main

2023-12-22 06:49 UTC, Rozzii commented
Ironic from source doesn't mean that the image is being built from source, it means that ironic is installed from source not a package into the image. that is why it was checking the directory name because it copies the source code to the ironic-image directory, so I think there is a misunderstanding here.
/hold

2023-12-22 06:49 UTC, Rozzii requested changes
/lgtm

2023-12-22 06:51 UTC, Rozzii approved these changes

2023-12-22 06:52 UTC, Rozzii commented
/hold cancel

2023-12-22 07:09 UTC, lentzi90 reviewed
/approve

2023-12-22 08:08 UTC, Sunnatillo reviewed
/lgtm

2023-12-22 08:09 UTC, merged