WIP Add support for TLS setup for Ironic
metal3-io/metal3-dev-env pull request #454
Opened 2020-09-15 07:53 UTC by maelk

This PR introduces a TLS setup for Ironic. It requires the following PRs to be merged :

- https://github.com/metal3-io/cluster-api-provider-metal3/pull/133
- https://github.com/metal3-io/baremetal-operator/pull/631
- https://github.com/metal3-io/ironic-inspector-image/pull/62
- https://github.com/metal3-io/ironic-image/pull/198

2020-09-15 19:28 UTC, maelk commented
/test-integration
/test-centos-integration
/hold until other PRs are merged

2020-09-16 06:18 UTC, kashifest requested changes

2020-09-16 06:18 UTC, kashifest commented on 03_launch_mgmt_cluster.sh
> +        BMO_CONFIG="${BMOPATH}/deploy/tls"
shouldn't it be the other way around?

2020-09-16 06:18 UTC, kashifest commented on 03_launch_mgmt_cluster.sh
> +        BMO_CONFIG="${BMOPATH}/ironic-deployment/keepalived-tls"
And this one also?

2020-09-16 07:38 UTC, maelk commented on 03_launch_mgmt_cluster.sh
> +        BMO_CONFIG="${BMOPATH}/deploy/tls"
good catch

2020-09-19 10:01 UTC, fmuyassarov commented on 03_launch_mgmt_cluster.sh
> -
This you have already done in #456 :)

2020-09-20 07:37 UTC, maelk commented on 03_launch_mgmt_cluster.sh
> -
rebased, thanks

2020-09-24 11:28 UTC, fmuyassarov commented on 03_launch_mgmt_cluster.sh
> +        cp "${IRONIC_CACERT_FILE}" "${BMOPATH}/ironic-deployment/tls/keepalived/ironic-inspector-ca.crt"
```suggestion
        cp "${IRONIC_INSPECTOR_CACERT_FILE}" "${BMOPATH}/ironic-deployment/tls/keepalived/ironic-inspector-ca.crt"
```
?

2020-09-24 15:16 UTC, maelk commented on 03_launch_mgmt_cluster.sh
> +        cp "${IRONIC_CACERT_FILE}" "${BMOPATH}/ironic-deployment/tls/keepalived/ironic-inspector-ca.crt"
done

2020-10-06 10:43 UTC, maelk commented
/test-integration

2020-10-08 14:55 UTC, closed without merging