Remove post_pivot script for feature test
metal3-io/metal3-dev-env pull request #770
Opened 2021-08-20 10:07 UTC by kashifest

This PR removes post_pivot script for feature test. This script was added initially to check an operation after the pivot works or not. Currently in features test we run node_reuse after pivot so we don't need it anymore.

2021-08-20 10:08 UTC, kashifest commented
/test-integration
/test-v1a4-centos-integration
/test-features

2021-08-20 11:52 UTC, mboukhalfa commented
> /test-integration
> /test-v1a4-centos-integration
> /test-features

The test-features fails until we got the PR #766 merged

2021-08-23 05:51 UTC, kashifest commented
/test-features

2021-08-23 11:51 UTC, kashifest commented
/test-features

2021-08-23 14:17 UTC, furkatgofurov7 requested changes

2021-08-23 14:17 UTC, furkatgofurov7 commented on vm-setup/roles/v1aX_integration_test/tasks/post_pivot.yml
> -    ignore_errors: yes
You need these lines in the beginning of `node_reuse.yml` file, specifically before the:
`   - name: Scale worker down to 0 to start testing KubeadmControlPlane node reuse test scenario.` task. 
I went inside the VM while running the feature tests and saw BMO and Ironic Pod in `pending` state in target cluster. Untainting nodes helped BMO and ironic pods to become in `running` state and pass the step where it was failing previously.

2021-08-23 16:21 UTC, kashifest commented
/test-integration
/test-v1a4-centos-integration
/test-features

2021-08-24 06:05 UTC, furkatgofurov7 commented
Failed in remediation, re-triggering. 
/test-features

2021-08-24 10:59 UTC, kashifest commented
/test-features

2021-08-24 21:07 UTC, furkatgofurov7 commented
/test-features

2021-08-25 06:31 UTC, furkatgofurov7 approved these changes
/approve

2021-08-25 06:39 UTC, jan-est commented
/lgtm

2021-08-25 06:40 UTC, merged