Add git configuration options for BMO
metal3-io/metal3-dev-env pull request #805
Opened 2021-09-24 11:09 UTC by Rozzii

This change also adds logic to automatically save git metadata
to a metadata file.

2021-09-24 11:10 UTC, Rozzii commented
/cc @fmuyassarov
/cc @kashifest 
/cc @smoshiur1237

2021-09-24 11:42 UTC, Rozzii commented
/test-integration
/test-v1a4-centos-integration

2021-09-27 07:59 UTC, kashifest commented on 03_launch_mgmt_cluster.sh
> +    echo "${REPO_URL}:${REPO_BRANCH}:$(git rev-parse --short HEAD)" >> "${IPA_BUILD_METADATA_LOCATION}"
Lets move this to Nordix/IPA building scripts

2021-09-27 08:00 UTC, kashifest requested changes
Lets move the IPA related work in Nordix

2021-09-27 08:46 UTC, Rozzii commented
/test-v1a4-centos-integration 
/test-integration

2021-09-27 09:54 UTC, fmuyassarov reviewed
/lgtm

2021-09-27 10:26 UTC, smoshiur1237 commented
Looks good to me

2021-09-28 11:50 UTC, fmuyassarov commented
/lgtm cancel
/approve

2021-09-28 11:52 UTC, smoshiur1237 commented
/lgtm

2021-09-28 11:52 UTC, merged