Add kubernetes pip dependecy handling to renovate
metal3-io/metal3-dev-env pull request #874
Opened 2021-11-24 10:09 UTC by Rozzii

This dependency is used by one of Ansible's collections/plugins
named kubernetes.core.

2021-11-24 10:10 UTC, Rozzii commented
/test-v1a5-centos-integration
/test-v1b1-integration

2021-11-24 11:55 UTC, Rozzii commented
/test-v1a5-centos-integration
/test-v1b1-integration

2021-11-24 12:03 UTC, Rozzii commented
/cc @fmuyassarov 
/cc @Sunnatillo

2021-11-24 15:00 UTC, Rozzii commented
/retest

2021-11-25 07:43 UTC, Rozzii commented
/test-v1a5-centos-integration
/test-v1b1-integration

2021-11-25 08:11 UTC, fmuyassarov requested changes

2021-11-25 08:11 UTC, fmuyassarov commented on renovate.json
> +       "matchStrings": ["kbuernetes==(?<currentValue>.*?)"],
```suggestion
       "matchStrings": ["kubuernetes==(?<currentValue>.*?)"],
```

2021-11-25 08:14 UTC, Rozzii commented
/test-v1a5-centos-integration
/test-v1b1-integration

2021-11-25 08:14 UTC, Rozzii commented on renovate.json
> +       "matchStrings": ["kbuernetes==(?<currentValue>.*?)"],
Thanks, fixed it.

2021-11-25 08:21 UTC, Sunnatillo reviewed
Looks good to me

2021-11-25 08:27 UTC, fmuyassarov approved these changes

2021-11-25 09:11 UTC, kashifest approved these changes

2021-11-25 09:11 UTC, kashifest commented
/lgtm

2021-11-25 13:18 UTC, Rozzii commented
/retest

2021-11-25 13:18 UTC, Rozzii commented
/test-v1a5-centos-integration
/test-v1b1-integration

2021-11-25 17:48 UTC, Rozzii commented
/test-v1a5-centos-integration

2021-11-25 18:41 UTC, merged