Check ironic deployment instead of pods after pivot
metal3-io/metal3-dev-env pull request #983
Opened 2022-04-05 13:11 UTC by mboukhalfa

fix #981

2022-04-05 13:13 UTC, mboukhalfa commented
/test-v1b1-ubuntu-integration

2022-04-05 14:03 UTC, mboukhalfa commented
/assign @kashifest 
cc @lentzi90

2022-04-05 14:08 UTC, lentzi90 reviewed
This looks good to me!
Can you add also a check for BMO? I think we should check both Ironic and BMO deployments. The old check was for all pods in the cluster but I think the main point here is to see that Ironic and BMO are healthy.

2022-04-05 14:18 UTC, mboukhalfa commented
/test-v1a5-centos-integration

2022-04-05 15:25 UTC, kashifest commented
I would rather keep the pods check, it was done for multiple reason, one particular reason being, the provider components needs to be up and running before the pivot operation, you can add the deployment check in addition but do it in a loop for ironic and bmo rather than adding two different tasks.

2022-04-05 15:36 UTC, mboukhalfa commented
/test-v1a5-centos-integration
/test-v1b1-ubuntu-integration

2022-04-06 05:21 UTC, lentzi90 commented
> I would rather keep the pods check, it was done for multiple reason, one particular reason being, the provider components needs to be up and running before the pivot operation, you can add the deployment check in addition but do it in a loop for ironic and bmo rather than adding two different tasks.

I guess the question then is if we should check the provider components also with the deployment check? As we have seen with Ironic, the "pods are running" check does not capture crash-looping pods in a good way.

2022-04-06 05:53 UTC, kashifest commented
> > I would rather keep the pods check, it was done for multiple reason, one particular reason being, the provider components needs to be up and running before the pivot operation, you can add the deployment check in addition but do it in a loop for ironic and bmo rather than adding two different tasks.
> 
> I guess the question then is if we should check the provider components also with the deployment check? As we have seen with Ironic, the "pods are running" check does not capture crash-looping pods in a good way.

Yeah thats what I meant

2022-04-08 09:31 UTC, lentzi90 reviewed
The check looks good to me but it is quite spammy in the logs. Would it be possible to reduce the output somehow?

2022-04-08 09:31 UTC, lentzi90 commented on vm-setup/roles/v1aX_integration_test/tasks/move.yml
> +    register: ironic_bmo_deployments
This is all deployment, right?
```suggestion
    register: deployments
```

2022-04-08 11:49 UTC, mboukhalfa commented
/test-v1a5-centos-integration
/test-v1b1-ubuntu-integration

2022-04-14 05:26 UTC, lentzi90 commented
/test-v1b1-ubuntu-integration

2022-04-14 05:26 UTC, lentzi90 commented
/test-v1b1-ubuntu-integration

2022-04-14 05:27 UTC, lentzi90 commented
/test-v1b1-ubuntu-integration

2022-04-14 06:17 UTC, kashifest commented
/test-v1a5-centos-integration 
/lgtm

2022-04-14 06:48 UTC, lentzi90 requested changes
The functionality is good, but it is still way too spammy I think.
Check the logs at "Check if pods in running state" and "Check if all deployments replicas are available". It is huge!

2022-04-14 07:43 UTC, mboukhalfa commented
> Check if all deployments replicas are available

it is printing some warnings when could not find the unavailable replicas he warning print the full deployment yaml. I can replace the full yaml with the deployment name or omit completely the warning but the final out put it also print all deployments yaml and that is how our ansible verbosity is configured do you want to reduce that also ?

2022-04-14 08:06 UTC, lentzi90 commented
> > Check if all deployments replicas are available
> 
> it is printing some warnings when could not find the unavailable replicas the warning print the full deployment yaml. I can replace the full yaml with the deployment name or omit completely the warning but the final out put it also print all deployments yaml and that is how our ansible verbosity is configured do you want to reduce that also ?

I would say getting rid of the warning is the most important part. The normal print is ok.

2022-04-14 08:15 UTC, mboukhalfa commented
/test-v1b1-ubuntu-integration
/test-v1a5-centos-integration

2022-04-14 09:51 UTC, lentzi90 commented
/lgtm

2022-04-14 09:56 UTC, mboukhalfa commented
/test-v1a5-centos-integration

2022-04-14 13:44 UTC, fmuyassarov approved these changes

2022-04-14 13:44 UTC, merged